[package]
name = "voxov"
version = "0.1.0"
authors = ["Celio Grand <celiogrand@outlook.com>"]
edition = "2021"
license = "AGPL-3.0-or-later"
rust-version = "1.68"
description = "A Pay-as-You-Go Backend-as-a-Service server"
#TODO documentation
readme = "README.md"
#TODO homepage
repository = "https://github.com/vorgv/voxov/"
keywords = ["payg", "baas"]
categories = ["web-programming"]

[dependencies]
tokio = { version = "1.27.0", features = ["full"] }
bytes = "1.4"

hyper = { version = "1.0.0-rc.3", features = ["full"] }
http-body-util = "0.1.0-rc.2"
serde_json = "1.0"

redis = { version = "0.23.0", features = ["tokio-comp"] }
rand = "0.8.5"
hex = "0.4"
