[workspace]
members = ["cli"]

[workspace.dependencies]
tokio = { version = "1.29.1", features = ["full"] }

[package]
name = "voxov"
version = "0.1.0"
authors = ["Celio Grand <celiogrand@outlook.com>"]
edition = "2021"
license = "AGPL-3.0-or-later"
rust-version = "1.68"
description = "A Pay-as-You-Go Backend-as-a-Service server"
#TODO documentation
readme = "README.md"
#TODO homepage
repository = "https://github.com/vorgv/voxov/"
keywords = ["payg", "baas"]
categories = ["web-programming"]

[dependencies]
# Tokio
tokio = { workspace = true }
tokio-util = "0.7.8"
tokio-stream = "0.1.14"
bytes = "1.4"

# Hyper
hyper = { version = "1.0.0-rc.3", features = ["full"] }
http-body-util = "0.1.0-rc.2"

# Database
redis = { version = "0.23.0", features = ["tokio-comp", "connection-manager"] }
mongodb = "2.6.0"
bson = { version = "2.6.1", features = ["chrono-0_4"] }
rust-s3 = { version = "0.33.0", features = ["with-tokio"] }

# Tools
blake3 = "1.4.0"
chrono = "0.4.26"
rand = "0.8.5"
hex = "0.4"

# Macros
strum_macros = "0.25"
serde = "1.0.164"
serde_json = "1.0.99"
console-subscriber = "0.1.10"
