# An example of testing server.
services:
  voxov:
    # Pull *OR* build the image.
    image: "c31io/voxov"
    #build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: "redis://redis"
      MONGO_ADDR: "mongodb://mongo"
      S3_ADDR: "http://minio:9000"
      SAMSARA: "1"
      HTTP_ADDR: "0.0.0.0:8080"
      SKIP_AUTH: "1"

  redis:
    image: "redis"

  mongo:
    image: "mongo"

  minio:
    image: "minio/minio"
