# An example of testing server.
services:
  voxov:
    # Pull *OR* build the image.
    image: "c31io/voxov"
    #build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: "redis://redis"
      MONGO_ADDR: "mongodb://mongo"
      S3_ADDR: "http://minio:9000"
      S3_ACCESS_KEY: "example-user"
      S3_SECRET_KEY: "example-password"
      SAMSARA: "1"
      HTTP_ADDR: "0.0.0.0:8080"
      # Comment SKIP_AUTH if testing.
      SKIP_AUTH: "1"
    depends_on:
      - redis
      - mongo
      - minio

  redis:
    extends:
      file: ./deploy/docker/databases/compose.yaml
      service: redis

  mongo:
    extends:
      file: ./deploy/docker/databases/compose.yaml
      service: mongo

  minio:
    extends:
      file: ./deploy/docker/databases/compose.yaml
      service: minio

  minio-create-bucket:
    extends:
      file: ./deploy/docker/databases/compose.yaml
      service: minio-create-bucket
    depends_on:
      - minio
