# An example of testing server.
services:
  voxov:
    # Pull *OR* build the image.
    image: "c31io/voxov"
    #build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: "redis://redis"
      MONGO_ADDR: "mongodb://mongo"
      S3_ADDR: "http://minio:9000"
      S3_ACCESS_KEY: "example-user"
      S3_SECRET_KEY: "example-password"
      SAMSARA: "1"
      HTTP_ADDR: "0.0.0.0:8080"
      # Comment SKIP_AUTH if testing.
      SKIP_AUTH: "1"
    depends_on:
      - redis
      - mongo
      - minio

  redis:
    image: "redis"
    ports:
      - "127.0.0.1:6379:6379"

  mongo:
    image: "mongo"
    ports:
      - "127.0.0.1:27017:27017"

  minio:
    image: "minio/minio"
    command: minio server --console-address ":9001" /data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_ROOT_USER: "example-user"
      MINIO_ROOT_PASSWORD: "example-password"

  minio-create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 example-user example-password;
      /usr/bin/mc mb myminio/voxov;
      /usr/bin/mc policy set public myminio/voxov;
      exit 0;
      "
