# An example of testing server.
services:
  voxov:
    # Pull *OR* build the image.
    image: "c31io/voxov"
    #build: .
    ports:
      - "8080:8080"
    environment:
      SCYLLA_ADDR: "scylla:9042"
      CRDB_ADDR: "postgresql://root@cockroachdb:26257/voxov?sslmode=disable"
      S3_ADDR: "http://garage:3900"
      S3_REGION: "garage"
      S3_ACCESS_KEY: "${S3_ACCESS_KEY}"
      S3_SECRET_KEY: "${S3_SECRET_KEY}"
      SAMSARA: "1"
      HTTP_ADDR: "0.0.0.0:8080"
      # Comment SKIP_AUTH before cargo test.
      SKIP_AUTH: "1"
    depends_on:
      - scylla
      - cockroachdb
      - garage

  scylla:
    extends:
      file: ./deploy/docker/databases/compose.yaml
      service: scylla

  cockroachdb:
    extends:
      file: ./deploy/docker/databases/compose.yaml
      service: cockroachdb

  cockroachdb-init:
    extends:
      file: ./deploy/docker/databases/compose.yaml
      service: cockroachdb-init
    depends_on:
      - cockroachdb

  garage:
    extends:
      file: ./deploy/docker/databases/compose.yaml
      service: garage
