// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Device defines model for device.
type Device struct {
	Created *string  `json:"created,omitempty"`
	Did     *string  `json:"did,omitempty"`
	Dinfo   *string  `json:"dinfo,omitempty"`
	Dname   *string  `json:"dname,omitempty"`
	Dtoken  *string  `json:"dtoken,omitempty"`
	LastIn  *string  `json:"last_in,omitempty"`
	Pid     *string  `json:"pid,omitempty"`
	Session *Session `json:"session,omitempty"`
}

// Person defines model for person.
type Person struct {
	Balance *string  `json:"balance,omitempty"`
	Created *string  `json:"created,omitempty"`
	Dlimit  *string  `json:"dlimit,omitempty"`
	Hid     *string  `json:"hid,omitempty"`
	IdDoc   *string  `json:"id_doc,omitempty"`
	LastIn  *string  `json:"last_in,omitempty"`
	Phone   *string  `json:"phone,omitempty"`
	Pid     string   `json:"pid"`
	Pname   *string  `json:"pname,omitempty"`
	Session *Session `json:"session,omitempty"`
}

// PersonId defines model for person_id.
type PersonId struct {
	Documents *map[string]string `json:"documents,omitempty"`
	Person    *Person            `json:"person,omitempty"`
	Session   *Session           `json:"session,omitempty"`
}

// Result defines model for result.
type Result struct {
	Info *string `json:"info,omitempty"`
	Ok   *bool   `json:"ok,omitempty"`
}

// Session defines model for session.
type Session struct {
	Pid    *string `json:"pid,omitempty"`
	Result *Result `json:"result,omitempty"`
	Sid    string  `json:"sid"`
	Ttl    *string `json:"ttl,omitempty"`
}

// SmsAuth defines model for sms_auth.
type SmsAuth struct {
	Msg     string   `json:"msg"`
	Session *Session `json:"session,omitempty"`
	Tel     string   `json:"tel"`
}

// Transfer defines model for transfer.
type Transfer struct {
	FromPid *string  `json:"from_pid,omitempty"`
	Note    *string  `json:"note,omitempty"`
	Session *Session `json:"session,omitempty"`
	Tid     string   `json:"tid"`
	ToPid   *string  `json:"to_pid,omitempty"`
	Ttime   *string  `json:"ttime,omitempty"`
	Volume  *string  `json:"volume,omitempty"`
}

// DeleteDeviceJSONRequestBody defines body for DeleteDevice for application/json ContentType.
type DeleteDeviceJSONRequestBody = Device

// GetDeviceJSONRequestBody defines body for GetDevice for application/json ContentType.
type GetDeviceJSONRequestBody = Device

// PostDeviceJSONRequestBody defines body for PostDevice for application/json ContentType.
type PostDeviceJSONRequestBody = Device

// PutDeviceJSONRequestBody defines body for PutDevice for application/json ContentType.
type PutDeviceJSONRequestBody = Device

// PutPersonIdJSONRequestBody defines body for PutPersonId for application/json ContentType.
type PutPersonIdJSONRequestBody = PersonId

// GetPersonPhoneJSONRequestBody defines body for GetPersonPhone for application/json ContentType.
type GetPersonPhoneJSONRequestBody = SmsAuth

// DeleteSessionJSONRequestBody defines body for DeleteSession for application/json ContentType.
type DeleteSessionJSONRequestBody = Session

// GetSessionJSONRequestBody defines body for GetSession for application/json ContentType.
type GetSessionJSONRequestBody = Session

// PostSessionJSONRequestBody defines body for PostSession for application/json ContentType.
type PostSessionJSONRequestBody = Session

// PutSessionAuthDeviceJSONRequestBody defines body for PutSessionAuthDevice for application/json ContentType.
type PutSessionAuthDeviceJSONRequestBody = Device

// GetSessionAuthSmsJSONRequestBody defines body for GetSessionAuthSms for application/json ContentType.
type GetSessionAuthSmsJSONRequestBody = SmsAuth

// GetTransferJSONRequestBody defines body for GetTransfer for application/json ContentType.
type GetTransferJSONRequestBody = Transfer

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (DELETE /device)
	DeleteDevice(ctx echo.Context) error

	// (GET /device)
	GetDevice(ctx echo.Context) error

	// (POST /device)
	PostDevice(ctx echo.Context) error

	// (PUT /device)
	PutDevice(ctx echo.Context) error

	// (GET /pay)
	GetPay(ctx echo.Context) error

	// (GET /person)
	GetPerson(ctx echo.Context) error

	// (GET /person/id)
	GetPersonId(ctx echo.Context) error

	// (PUT /person/id)
	PutPersonId(ctx echo.Context) error

	// (GET /person/phone)
	GetPersonPhone(ctx echo.Context) error

	// (POST /person/phone)
	PostPersonPhone(ctx echo.Context) error

	// (DELETE /session)
	DeleteSession(ctx echo.Context) error

	// (GET /session)
	GetSession(ctx echo.Context) error

	// (POST /session)
	PostSession(ctx echo.Context) error

	// (PUT /session)
	PutSession(ctx echo.Context) error

	// (PUT /session/auth/device)
	PutSessionAuthDevice(ctx echo.Context) error

	// (GET /session/auth/sms)
	GetSessionAuthSms(ctx echo.Context) error

	// (PUT /session/auth/sms)
	PutSessionAuthSms(ctx echo.Context) error

	// (GET /transfer)
	GetTransfer(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteDevice converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteDevice(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteDevice(ctx)
	return err
}

// GetDevice converts echo context to params.
func (w *ServerInterfaceWrapper) GetDevice(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetDevice(ctx)
	return err
}

// PostDevice converts echo context to params.
func (w *ServerInterfaceWrapper) PostDevice(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostDevice(ctx)
	return err
}

// PutDevice converts echo context to params.
func (w *ServerInterfaceWrapper) PutDevice(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutDevice(ctx)
	return err
}

// GetPay converts echo context to params.
func (w *ServerInterfaceWrapper) GetPay(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPay(ctx)
	return err
}

// GetPerson converts echo context to params.
func (w *ServerInterfaceWrapper) GetPerson(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPerson(ctx)
	return err
}

// GetPersonId converts echo context to params.
func (w *ServerInterfaceWrapper) GetPersonId(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPersonId(ctx)
	return err
}

// PutPersonId converts echo context to params.
func (w *ServerInterfaceWrapper) PutPersonId(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutPersonId(ctx)
	return err
}

// GetPersonPhone converts echo context to params.
func (w *ServerInterfaceWrapper) GetPersonPhone(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPersonPhone(ctx)
	return err
}

// PostPersonPhone converts echo context to params.
func (w *ServerInterfaceWrapper) PostPersonPhone(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostPersonPhone(ctx)
	return err
}

// DeleteSession converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSession(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteSession(ctx)
	return err
}

// GetSession converts echo context to params.
func (w *ServerInterfaceWrapper) GetSession(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetSession(ctx)
	return err
}

// PostSession converts echo context to params.
func (w *ServerInterfaceWrapper) PostSession(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostSession(ctx)
	return err
}

// PutSession converts echo context to params.
func (w *ServerInterfaceWrapper) PutSession(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutSession(ctx)
	return err
}

// PutSessionAuthDevice converts echo context to params.
func (w *ServerInterfaceWrapper) PutSessionAuthDevice(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutSessionAuthDevice(ctx)
	return err
}

// GetSessionAuthSms converts echo context to params.
func (w *ServerInterfaceWrapper) GetSessionAuthSms(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetSessionAuthSms(ctx)
	return err
}

// PutSessionAuthSms converts echo context to params.
func (w *ServerInterfaceWrapper) PutSessionAuthSms(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PutSessionAuthSms(ctx)
	return err
}

// GetTransfer converts echo context to params.
func (w *ServerInterfaceWrapper) GetTransfer(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetTransfer(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(baseURL+"/device", wrapper.DeleteDevice)
	router.GET(baseURL+"/device", wrapper.GetDevice)
	router.POST(baseURL+"/device", wrapper.PostDevice)
	router.PUT(baseURL+"/device", wrapper.PutDevice)
	router.GET(baseURL+"/pay", wrapper.GetPay)
	router.GET(baseURL+"/person", wrapper.GetPerson)
	router.GET(baseURL+"/person/id", wrapper.GetPersonId)
	router.PUT(baseURL+"/person/id", wrapper.PutPersonId)
	router.GET(baseURL+"/person/phone", wrapper.GetPersonPhone)
	router.POST(baseURL+"/person/phone", wrapper.PostPersonPhone)
	router.DELETE(baseURL+"/session", wrapper.DeleteSession)
	router.GET(baseURL+"/session", wrapper.GetSession)
	router.POST(baseURL+"/session", wrapper.PostSession)
	router.PUT(baseURL+"/session", wrapper.PutSession)
	router.PUT(baseURL+"/session/auth/device", wrapper.PutSessionAuthDevice)
	router.GET(baseURL+"/session/auth/sms", wrapper.GetSessionAuthSms)
	router.PUT(baseURL+"/session/auth/sms", wrapper.PutSessionAuthSms)
	router.GET(baseURL+"/transfer", wrapper.GetTransfer)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9yYzY7bNhDHX4Vge2gBb7Rpb741CRAEaAujbk9BYNDS2GJW4rDkyKkR+N0LkpL1YdK7",
	"ae0s4pstjsj//GbIGeozz7HWqECR5fPP3OYl1ML/LGAnc3C/tEENhiT457kBQVC4n7TXwOfckpFqyw8z",
	"XsjUc7XB+IgSNcRHCB9ARYcqYWkl42M6IcGCtRL9O98b2PA5/y7rfc9ax7PO7HCYdXPg+iPk5OcGY8MU",
	"YyRrUQmVx904i6uStaToUJlwQxarAvMvp1Kigi/ipZOB+Q8kDfzdSOMovPcLfkjCXQU5Y74F5k3dpago",
	"CkkSlagWI6MTnWfCd053a3WhlDFgm4pOXUpuCHwYPF4jViASUw/kjedOhbTXcs6d1sotkJiHqIo8n4TZ",
	"JsJsa7sSDZWnsmu7vUi+zTjBEwQ6o5lfNCaTjFB2A+ZU5sZgvUohVkhwKSdS9DG5OpFM7NkdVk10aAol",
	"GjVn1SVsATY3UpN3hi/E/k7Yuz02d1tkr4RYcqecKvf6Dv/BHZ/xHZjgO3/54v7Fvc9yDUpoyef8Z/9o",
	"xrWg0vPN+sJTQAWBpwuAcGu+K/icv/HP3wS74ABYeoXF3hcoVATK57nQupK5fzH72O79gPqxQLQiDodA",
	"yGpUNsT/p/v7i63S7TW3yBjsH1DjDliQ8YP9MdhsgU5pvAX6RlBIgto+dbljFgpjxD7G6C1QC4it9yxH",
	"FQpDMNVoI6wWaOmm8+YvXQjq8oa5Gs6EKjI0zG3gWgwANTE+zS3g6VeZ4nntuzEmmIJPbCQm08K7mdpi",
	"C7Hn/1Py9OiNJnQpFVmGipX4iREyHXLfKzz2L0mRweKKaLvuKC4+jE5SrZeehbp1Xv27gj/LznH6ZQGK",
	"5KadmlkS1Njz22Uk+vIbpu+Kn/FIqVAUUzZ9Tz4O8fGmcT7KC292HWbHFvPKyNJ74XUJ+QPzKJhq6jWY",
	"cS4la9MUzpWUDwmdahdqC2PxOynY8rdlF+pBM3u+RVu2hleK8/HiddUwD5aZsloSapY3xoAiNrJLZf+t",
	"E3GnaBRIOudvHUnbksWpJKrKkMnXV9x2SWN03QuZOzgGl7RHXPilofKmW0rnoKuMuUPmDsq29w6fL2Ps",
	"bLgEPXJEuHmXtb3xGil6ek/tuCJ8nqFMjsI+2dvTejn8mJSK+p+dzXXifZTwta7x/YJPu8gL1r3B0LDf",
	"j/8sW8MGjbuz+a9bh+CABbMDY/n8/fST1K+Yi4qFcT7jjan4nJdEep5llRsr0VK2e8kPHw7/BgAA//+U",
	"YZDs/xgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
