//! Info gene returns information about this VOxOV instance,
//! including the maintainer, credit rate, and gene list.
//! The gene list is generated by macros,
//! and others are in the config struct.

pub async fn v1() -> String {
    "".to_string()
}
