// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Argument struct {
	Option *string `json:"option"`
	Value  *string `json:"value"`
}

type Auth struct {
	Method AuthMethod `json:"method"`
	Sid    *string    `json:"sid"`
	Sms    *Sms       `json:"sms"`
	TTL    *string    `json:"ttl"`
	Person *Person    `json:"person"`
	Device *Device    `json:"device"`
}

type AuthOutput struct {
	Auth *Auth  `json:"auth"`
	Err  *Error `json:"err"`
}

type Cost struct {
	Auth     *Auth     `json:"auth"`
	Kin      string    `json:"kin"`
	Pot      string    `json:"pot"`
	Plan     *Plan     `json:"plan"`
	Transfer *Transfer `json:"transfer"`
}

type CostOutput struct {
	Cost *Cost  `json:"cost"`
	Err  *Error `json:"err"`
}

type Device struct {
	Did     *string `json:"did"`
	Dtoken  *string `json:"dtoken"`
	Dname   *string `json:"dname"`
	Dinfo   *string `json:"dinfo"`
	Pid     *string `json:"pid"`
	Created *string `json:"created"`
	LastIn  *string `json:"last_in"`
}

type Error struct {
	Msg *string `json:"msg"`
}

type Metadata struct {
	Key   string  `json:"key"`
	Value *string `json:"value"`
}

type Person struct {
	Pid     *string `json:"pid"`
	Hid     *string `json:"hid"`
	Balance *string `json:"balance"`
	Phone   *string `json:"phone"`
	Pname   *string `json:"pname"`
	IDDoc   *string `json:"id_doc"`
	Dlimit  *string `json:"dlimit"`
	Created *string `json:"created"`
	LastIn  *string `json:"last_in"`
}

type Plan struct {
	PlanID  string `json:"plan_id"`
	Pid     string `json:"pid"`
	Rid     string `json:"rid"`
	Vlimit  string `json:"vlimit"`
	Billing string `json:"billing"`
}

type Potential struct {
	From  *string `json:"from"`
	To    *string `json:"to"`
	Value *string `json:"value"`
}

type Replicon struct {
	Cost   *Union          `json:"cost"`
	Method *RepliconMethod `json:"method"`
	Rid    *string         `json:"rid"`
	Type   *RepliconType   `json:"type"`
	Pots   []*Potential    `json:"pots"`
	Metas  []*Metadata     `json:"metas"`
	Args   []*Argument     `json:"args"`
	Body   *string         `json:"body"`
}

type RepliconOutput struct {
	Replicon *Replicon `json:"replicon"`
	Err      *Error    `json:"err"`
}

type Sms struct {
	Tel string `json:"tel"`
	Msg string `json:"msg"`
}

type Transfer struct {
	Tid     *string `json:"tid"`
	FromPid *string `json:"from_pid"`
	ToPid   *string `json:"to_pid"`
	Volume  *string `json:"volume"`
	Note    *string `json:"note"`
	Ttime   *string `json:"ttime"`
}

type Union struct {
	Cost *Cost   `json:"cost"`
	URL  *string `json:"url"`
	Info *string `json:"info"`
}

type UnionOutput struct {
	Union *Union `json:"union"`
	Err   *Error `json:"err"`
}

type AuthMethod string

const (
	AuthMethodStart   AuthMethod = "START"
	AuthMethodAuth    AuthMethod = "AUTH"
	AuthMethodKeep    AuthMethod = "KEEP"
	AuthMethodExtend  AuthMethod = "EXTEND"
	AuthMethodRefresh AuthMethod = "REFRESH"
	AuthMethodEnd     AuthMethod = "END"
)

var AllAuthMethod = []AuthMethod{
	AuthMethodStart,
	AuthMethodAuth,
	AuthMethodKeep,
	AuthMethodExtend,
	AuthMethodRefresh,
	AuthMethodEnd,
}

func (e AuthMethod) IsValid() bool {
	switch e {
	case AuthMethodStart, AuthMethodAuth, AuthMethodKeep, AuthMethodExtend, AuthMethodRefresh, AuthMethodEnd:
		return true
	}
	return false
}

func (e AuthMethod) String() string {
	return string(e)
}

func (e *AuthMethod) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuthMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuthMethod", str)
	}
	return nil
}

func (e AuthMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type RepliconMethod string

const (
	RepliconMethodHeader RepliconMethod = "HEADER"
	RepliconMethodBody   RepliconMethod = "BODY"
	RepliconMethodAll    RepliconMethod = "ALL"
)

var AllRepliconMethod = []RepliconMethod{
	RepliconMethodHeader,
	RepliconMethodBody,
	RepliconMethodAll,
}

func (e RepliconMethod) IsValid() bool {
	switch e {
	case RepliconMethodHeader, RepliconMethodBody, RepliconMethodAll:
		return true
	}
	return false
}

func (e RepliconMethod) String() string {
	return string(e)
}

func (e *RepliconMethod) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepliconMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepliconMethod", str)
	}
	return nil
}

func (e RepliconMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type RepliconType string

const (
	RepliconTypeGene RepliconType = "GENE"
	RepliconTypeMeme RepliconType = "MEME"
)

var AllRepliconType = []RepliconType{
	RepliconTypeGene,
	RepliconTypeMeme,
}

func (e RepliconType) IsValid() bool {
	switch e {
	case RepliconTypeGene, RepliconTypeMeme:
		return true
	}
	return false
}

func (e RepliconType) String() string {
	return string(e)
}

func (e *RepliconType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RepliconType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RepliconType", str)
	}
	return nil
}

func (e RepliconType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
