services:
  scylla:
    image: "scylladb/scylla:5.4"
    ports:
      - "127.0.0.1:9042:9042"
    command: --smp 1 --memory 512M --overprovisioned 1

  cockroachdb:
    image: "cockroachdb/cockroach:v23.2.0"
    ports:
      - "127.0.0.1:26257:26257"
      - "127.0.0.1:8081:8080"
    command: start-single-node --insecure --store=type=mem,size=1GB

  cockroachdb-init:
    image: "cockroachdb/cockroach:v23.2.0"
    depends_on:
      - cockroachdb
    entrypoint: /bin/sh
    command: >
      -c "
      sleep 5;
      /cockroach/cockroach sql --insecure --host=cockroachdb:26257 -e 'CREATE DATABASE IF NOT EXISTS voxov';
      exit 0;
      "

  garage:
    image: "dxflrs/garage:v2.2.0"
    ports:
      - "127.0.0.1:3900:3900"
      - "127.0.0.1:3903:3903"
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - garage-meta:/var/lib/garage/meta
      - garage-data:/var/lib/garage/data

volumes:
  garage-meta:
  garage-data:
