services:
  redis:
    image: "redis"
    ports:
      - "127.0.0.1:6379:6379"

  mongo:
    image: "mongo"
    ports:
      - "127.0.0.1:27017:27017"

  minio:
    image: "minio/minio"
    command: minio server --console-address ":9001" /data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_ROOT_USER: "example-user"
      MINIO_ROOT_PASSWORD: "example-password"

  minio-create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 example-user example-password;
      /usr/bin/mc mb myminio/voxov;
      /usr/bin/mc policy set public myminio/voxov;
      exit 0;
      "
