package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/vorgv/voxov/api/model"
)

// Auth is the resolver for the auth field.
func (r *queryResolver) Auth(ctx context.Context) (*model.AuthOutput, error) {
	panic(fmt.Errorf("not implemented: Auth - auth"))
}

// Cost is the resolver for the cost field.
func (r *queryResolver) Cost(ctx context.Context) (*model.CostOutput, error) {
	panic(fmt.Errorf("not implemented: Cost - cost"))
}

// Union is the resolver for the union field.
func (r *queryResolver) Union(ctx context.Context) (*model.UnionOutput, error) {
	panic(fmt.Errorf("not implemented: Union - union"))
}

// Replicon is the resolver for the replicon field.
func (r *queryResolver) Replicon(ctx context.Context) (*model.RepliconOutput, error) {
	panic(fmt.Errorf("not implemented: Replicon - replicon"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
