package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/vorgv/voxov/api/model"
)

func (r *Resolver) Auth(ctx context.Context, input model.Auth) (*model.Auth, error) {
	panic(fmt.Errorf("not implemented: CreateSession"))
}
