openapi: 3.0.0

info:
  title: voxov
  description: Pay-as-you-go BaaS
  version: 1.0.0

servers:
  - url: http://localhost/v1
    description: Local server

components:
  schemas:
    result:
      type: object
      properties:
        ok:
          type: boolean
        info:
          type: string

    session:
      type: object
      properties:
        sid:
          type: string
        pid:
          type: string
        ttl:
          type: string
        result:
          $ref: "#/components/schemas/result"
      required:
        - sid

    person:
      type: object
      properties:
        pid:
          type: string
        hid:
          type: string
        balance:
          type: string
        phone:
          type: string
        pname:
          type: string
        id_doc:
          type: string
        dlimit:
          type: string
        created:
          type: string
        last_in:
          type: string
        session:
          $ref: "#/components/schemas/session"
      required:
        - pid

    device:
      type: object
      properties:
        did:
          type: string
        dtoken:
          type: string
        dname:
          type: string
        dinfo:
          type: string
        pid:
          type: string
        created:
          type: string
        last_in:
          type: string
        session:
          $ref: "#/components/schemas/session"

    transfer:
      type: object
      properties:
        tid:
          type: string
        from_pid:
          type: string
        to_pid:
          type: string
        volume:
          type: string
        note:
          type: string
        ttime:
          type: string
        session:
          $ref: "#/components/schemas/session"
      required:
        - tid

    plan:
      type: object
      properties:
        plan_id:
          type: string
        pid:
          type: string
        gid:
          type: string
        vlimit:
          type: string
        billing:
          type: string
        session:
          $ref: "#/components/schemas/session"
      required:
        - plan_id

    meme:
      type: object
      properties:
        hash:
          type: string
        cap:
          type: object
          additionalProperties:
            type: string
        tags:
          type: array
          items:
            type: string
        session:
          $ref: "#/components/schemas/session"
      required:
        - hash

    gene:
      type: object
      properties:
        hash:
          type: string
        cap:
          type: object
          additionalProperties:
            type: string
        tags:
          type: array
          items:
            type: string
        args:
          type: array
          items:
            type: string
        session:
          $ref: "#/components/schemas/session"
      required:
        - hash

    sms_auth:
      type: object
      properties:
        tel:
          type: string
        msg:
          type: string
        session:
          $ref: "#/components/schemas/session"
      required:
        - tel
        - msg

    person_id:
      type: object
      properties:
        person:
          $ref: "#/components/schemas/person"
        documents:
          type: object
          additionalProperties:
            type: string
        session:
          $ref: "#/components/schemas/session"

paths:
  /session:
    put:
      responses:
        "200":
          description: Create session
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/session"
    get:
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/session"
      responses:
        "200":
          description: Get current session
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/session"
    post:
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/session"
      responses:
        "200":
          description: Update current session
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/session"
    delete:
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/session"
      responses:
        "200":
          description: Stop current session
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/session"

  /session/auth/sms:
    put:
      responses:
        "200":
          description: Authenticate current session via SMS
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/sms_auth"
    get:
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/sms_auth"
      responses:
        "200":
          description: Check authentication status
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/person"

  /session/auth/device:
    put:
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/device"
      responses:
        "200":
          description: Authenticate via device token
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/device"

  /person:
    get:
      responses:
        "200":
          description: Get person infomation
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/person"

  /person/phone:
    post:
      responses:
        "200":
          description: Change phone number via SMS
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/sms_auth"
    get:
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/sms_auth"
      responses:
        "200":
          description: Check phone number status
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/person"

  /person/id:
    put:
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/person_id"
      responses:
        "200":
          description: Upload identification documents
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/result"
    get:
      responses:
        "200":
          description: Get identification status
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/result"

  /device:
    put:
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/device"
      responses:
        "200":
          description: Create a new device
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/device"
    get:
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/device"
      responses:
        "200":
          description: Get device by condition
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/device"
    post:
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/device"
      responses:
        "200":
          description: Update device name and/or infomation
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/result"
    delete:
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/device"
      responses:
        "200":
          description: Remove device(s)
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/result"

  /pay:
    get:
      responses:
        "200":
          description: Get hints on how to pay
          content:
            "application/json":
              schema:
                type: string

  /transfer:
    get:
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/transfer"
      responses:
        "200":
          description: Get a transfer or N transfers before a time
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transfer"

  # /plan:

  # /meme:

  # /gene:
